[information]
name = "my_vivid"
background = "dark"
author = "Raphaele Salvatore Licciardo <raphaele.salvatore@outlook.de>"

[palette]
fg = "#D0D0D0"
vivid_fg_delimiter = "#ADBDB0"
bg = "NONE" 

alt_fg = "#a4a4a4"
alt_bg = "#252525"

vivid_grey = "#7E7E80"
vivid_green = "#AECDAF"
vivid_white = "#CBCBCB"
vivid_orange = "#CDA07C"
vivid_blue = "#697BFF"
vivid_blue2= "#77B0DA"
vivid_yellow = "#CFD481"
vivid_yellow2 = "#FEE592"
vivid_red = "#C27574"
vivid_purple = "#A38FA8"

line = "#3e3e3e"
dark_gray = "#404040"
gray = "#808080"
context = "#606060"
light_gray = "#cccccc"
menu_bg = "#202123"

blue = "#569CD6"
light_blue = "#77A4B3"
green = "#6A9955"
light_green = "#B5CEA8"
cyan = "#4EC9B0"
orange = "#CE9178"
yellow = "#DCDCAA"
yellow_orange = "#D7BA7D"
magenta = "#D16D9E"

cursor_fg = "#515052"
cursor_bg = "#AEAFAD"

sign_add = "#587c0c"
sign_change = "#0c7d9d"
sign_delete = "#94151b"

sign_add_alt = "#73C991"
sign_change_alt = "#CCA700"

error = "#C27574"
warn = "#C16700"
info = "#C8A04F"
hint = "#378EBB"

error_bg = "#31262d"
warn_bg = "#32302f"
info_bg = "#1e3135"
hint_bg = "#22323f"

reference = "#363636"
success_green = "#14C50B"
folder_blue = "#42A5F5"

ui_blue = "#213249"
ui2_blue = "#042A43"
ui3_blue = "#0487E0"
ui4_blue = "#5B94C7"
ui5_blue = "#083C5A"
ui6_blue = "#2D4F67"
ui_orange = "#CE9178"
ui2_orange = "#D7BA7D"
ui_purple = "#A38FA8"

[Editor]
Normal = "fg bg"
SignColumn = "- bg"
MsgArea = "fg bg"
ModeMsg = "fg alt_bg"
MsgSeparator = "fg bg"
SpellBad = "- - c vivid_red"
SpellCap = "- - c yellow"
SpellLocal = "- - u green"
SpellRare = "- - u vivid_purple"
NormalNC = "fg bg"
Pmenu = "light_gray menu_bg"
PmenuSel = "- ui2_blue"
WildMenu = "vivid_fg_delimiter ui2_blue"
CursorLineNr = "vivid_yellow2"
Folded = "gray alt_bg"
FoldColumn = "gray alt_bg"
LineNr = "gray -"
FloatBoder = "gray alt_bg"
Whitespace = "dark_gray"
VertSplit = "gray bg"
CursorLine = "- -"
CursorColumn = "- alt_bg"
ColorColumn = "- alt_bg"
NormalFloat = "- alt_bg"
Visual = "- ui6_blue"
VisualNOS = "- alt_bg"
WarningMsg = "error bg"
DiffText = "alt_bg sign_delete"
DiffAdd = "alt_bg sign_add"
DiffChange = "alt_bg sign_change"
DiffDelete = "alt_bg sign_delete"
QuickFixLine = "- ui2_blue"
PmenuSbar = "- alt_bg"
PmenuThumb = "- gray"
MatchWord = "- reference"
MatchParen = "hint reference"
MatchWordCur = "- reference"
MatchParenCur = "- reference"
Cursor = "cursor_fg cursor_bg"
lCursor = "cursor_fg cursor_bg"
CursorIM = "cursor_fg cursor_bg"
TermCursor = "cursor_fg cursor_bg"
TermCursorNC = "cursor_fg cursor_bg"
Conceal = "gray"
Directory = "folder_blue"
SpecialKey = "blue - b"
ErrorMsg = "error bg b"
Search = "- ui5_blue"
IncSearch = "- ui2_orange"
Substitute = "- ui2_orange"
MoreMsg = "orange"
Question = "orange"
EndOfBuffer = "bg"
NonText = "dark_gray"
TabLine = "light_gray line"
TabLineSel = "vivid_fg_delimiter line"
TabLineFill = "line line"

[Code]
Comment = "context"
Variable = "light_blue"
String = "vivid_green"
Character = "vivid_red"
Number = "vivid_yellow"
Float = "vivid_yellow"
Boolean = "vivid_orange"
Constant = "vivid_yellow"
Type = "vivid_orange"
Function = "vivid_red"
Keyword = "vivid_purple"
Conditional = "vivid_purple"
Repeat = "vivid_purple"
Operator = "vivid_grey"
PreProc = "vivid_purple"
Include = "vivid_purple"
Exception = "vivid_purple"
StorageClass = "vivid_white"
Structure = "vivid_white"
Typedef = "vivid_purple"
Define = "vivid_purple"
Macro = "vivid_orange"
Debug = "vivid_red"
Title = "vivid_orange - b"
Label = "vivid_orange"
SpecialChar = "vivid_orange"
Delimiter = "vivid_fg_delimiter"
SpecialComment = "vivid_fg_delimiter"
Tag = "vivid_orange"
Bold = "- - b"
Italic = "- - i"
Underlined = "- - u"
Ignore = "magenta - b"
TODO = "magenta - b"
Error = "error - b"
Statement = "vivid_purple"
Identifier = "fg"
PreCondit = "vivid_purple"
Special = "vivid_orange"

[Treesitter]
TSComment = "context - i"
TSVariable = "link:Variable"
TSString = "link:String"
TSStringRegex = "link:String"
TSStringEscape = "link:String"
TSCharacter = "link:String"
TSCharacterSpecial = "link:SpecialChar"
TSNumber = "link:Number"
TSFloat = "link:Float"
TSBoolean = "link:Boolean"
TSConstant = "link:Constant"
TSConstBuiltin = "link:Constant"
TSConstructor = "link:Type"
TSType = "link:Type"
TSInclude = "link:Include"
TSException = "link:Exception"
TSKeyword = "link:Keyword"
TSKeywordReturn = "link:Include"
TSKeywordOperator = "link:Include"
TSKeywordFunction = "link:Keyword"
TSFunction = "link:Function"
TSFuncBuiltin = "link:Type"
TSMethod = "link:Function"
TSFuncMacro = "link:Function"
TSConditional = "link:Conditional"
TSRepeat = "link:Repeat"
TSOperator = "link:Operator"
TSPreProc = "link:PreProc"
TSStorageClass = "link:StorageClass"
TSStructure = "link:Structure"
TSTypeDefinition = "link:Typedef"
TSDefine = "link:Define"
TSNote = "link:Comment"
TSTODO = "link:TODO"
TSDebug = "link:Debug"
TSDanger = "link:Error"
TSTitle = "link:Title"
TSLabel = "link:Label"
TSPunctDelimiter = "link:Delimiter"
TSTagDelimiter = "gray"
TSPunctBracket = "link:Delimiter"
TSPunctSpecial = "link:Delimiter"
TSTag = "link:Tag"
TSStrong = "link:Bold"
TSEmphasis = "link:Italic"
TSUnderline = "link:Underline"
TSStrike = "- - s"
TSStringSpecial = "fg"
TSEnvironmentName = "vivid_white"
TSVariableBuiltin = "vivid_white"
TSConstMacro = "vivid_blue"
TSTypeBuiltin = "vivid_white"
TSAnnotation = "vivid_orange"
TSNamespace = "vivid_white"
TSSymbol = "fg"
TSField = "link:Variable"
TSProperty = "light_blue"
TSParameter = "light_blue"
TSParameterReference = "light_blue"
TSAttribute = "vivid_white"
TSText = "fg"
TSTagAttribute = "light_blue - i"
TSError = "error"
TSWarning = "warn"
TSQueryLinterError = "error"
TSURI = "vivid_white - u"
TSMath = "yellow"
TSLiteral = "vivid_red"

[markdown]
markdownBlockquote = "orange"
markdownCode = "orange"
markdownCodeBlock = "orange"
markdownCodeDelimiter = "orange"
markdownH1 = "link:Title"
markdownH2 = "link:Title"
markdownH3 = "link:Title"
markdownH4 = "link:Title"
markdownH5 = "link:Title"
markdownH6 = "link:Title"
markdownHeadingDelimiter = "blue"
markdownHeadingRule = "fg - b"
markdownId = "link:Identifier"
markdownIdDeclaration = "blue"
markdownIdDelimiter = "light_gray"
markdownLinkDelimiter = "light_gray"
markdownBold = "blue - b"
markdownItalic = "link:Italic"
markdownBoldItalic = "yellow - bi"
markdownListMarker = "blue"
markdownOrderedListMarker = "vivid_purple"
markdownRule = "gray"
markdownUrl = "cyan - t"
markdownLinkText = "blue"
markdownFootnote = "orange"
markdownFootnoteDefinition = "orange"
markdownEscape = "yellow"

[Whichkey]
WhichKey = "vivid_purple"
WhichKeySeperator = "green"
WhichKeyGroup = "blue"
WhichKeyDesc = "fg"
WhichKeyFloat = "- alt_bg"

[Git]
SignAdd = "sign_add"
SignChange = "sign_change"
SignDelete = "sign_delete"
GitSignsAdd = "sign_add"
GitSignsChange = "sign_change"
GitSignsDelete = "sign_delete"

[LSP]
DiagnosticHint = "hint"
DiagnosticInfo = "info"
DiagnosticWarn = "warn"
DiagnosticError = "error"
DiagnosticOther = "ui_purple"
DiagnosticSignHint = "link:DiagnosticHint"
DiagnosticSignInfo = "link:DiagnosticInfo"
DiagnosticSignWarn = "link:DiagnosticWarn"
DiagnosticSignError = "link:DiagnosticError"
DiagnosticSignOther = "link:DiagnosticOther"
DiagnosticSignWarning = "link:DiagnosticWarn"
DiagnosticFloatingHint = "link:DiagnosticHint"
DiagnosticFloatingInfo = "link:DiagnosticInfo"
DiagnosticFloatingWarn = "link:DiagnosticWarn"
DiagnosticFloatingError = "link:DiagnosticError"
DiagnosticUnderlineHint = "- - c hint"
DiagnosticUnderlineInfo = "- - c info"
DiagnosticUnderlineWarn = "- - c warn"
DiagnosticUnderlineError = "- - c error"
DiagnosticSignInformation = "link:DiagnosticInfo"
DiagnosticVirtualTextHint = "hint hint_bg"
DiagnosticVirtualTextInfo = "info info_bg"
DiagnosticVirtualTextWarn = "warn warn_bg"
DiagnosticVirtualTextError = "error error_bg"

LspDiagnosticsError = "error"
LspDiagnosticsWarning = "warn"
LspDiagnosticsInfo = "info"
LspDiagnosticsInformation = "link:LspDiagnosticsInfo"
LspDiagnosticsHint = "hint"
LspDiagnosticsDefaultError = "link:LspDiagnosticsError"
LspDiagnosticsDefaultWarning = "link:LspDiagnosticsWarning"
LspDiagnosticsDefaultInformation = "link:LspDiagnosticsInfo"
LspDiagnosticsDefaultInfo = "link:LspDiagnosticsInfo"
LspDiagnosticsDefaultHint = "link:LspDiagnosticsHint"
LspDiagnosticsVirtualTextError = "link:DiagnosticVirtualTextError"
LspDiagnosticsVirtualTextWarning = "link:DiagnosticVirtualTextWarn"
LspDiagnosticsVirtualTextInformation = "link:DiagnosticVirtualTextInfo"
LspDiagnosticsVirtualTextInfo = "link:DiagnosticVirtualTextInfo"
LspDiagnosticsVirtualTextHint = "link:DiagnosticVirtualTextHint"
LspDiagnosticsFloatingError = "link:LspDiagnosticsError"
LspDiagnosticsFloatingWarning = "link:LspDiagnosticsWarning"
LspDiagnosticsFloatingInformation = "link:LspDiagnosticsInfo"
LspDiagnosticsFloatingInfo = "link:LspDiagnosticsInfo"
LspDiagnosticsFloatingHint = "link:LspDiagnosticsHint"
LspDiagnosticsSignError = "link:LspDiagnosticsError"
LspDiagnosticsSignWarning = "link:LspDiagnosticsWarning"
LspDiagnosticsSignInformation = "link:LspDiagnosticsInfo"
LspDiagnosticsSignInfo = "link:LspDiagnosticsInfo"
LspDiagnosticsSignHint = "link:LspDiagnosticsHint"

NvimTreeLspDiagnosticsError = "link:LspDiagnosticsError"
NvimTreeLspDiagnosticsWarning = "link:LspDiagnosticsWarning"
NvimTreeLspDiagnosticsInformation = "link:LspDiagnosticsInfo"
NvimTreeLspDiagnosticsInfo = "link:LspDiagnosticsInfo"
NvimTreeLspDiagnosticsHint = "link:LspDiagnosticsHint"

LspDiagnosticsUnderlineError = "link:DiagnosticUnderlineError"
LspDiagnosticsUnderlineWarning = "link:DiagnosticUnderlineWarn"
LspDiagnosticsUnderlineInformation = "link:DiagnosticUnderlineInfo"
LspDiagnosticsUnderlineInfo = "link:DiagnosticUnderlineInfo"
LspDiagnosticsUnderlineHint = "link:DiagnosticUnderlineHint"

LspReferenceRead = "- reference"
LspReferenceText = "- reference"
LspReferenceWrite = "- reference"

IlluminatedWordRead = "link:LspReferenceRead"
IlluminatedWordText = "link:LspReferenceText"
IlluminatedWordWrite = "link:LspReferenceWrite"

LspCodeLens = "context - i"
LspCodeLensSeparator = "context - i"

[Quickscope]
QuickScopePrimary = "#ff007c - u"
QuickScopeSecondary = "#00dfff - u"

[Telescope]
TelescopeSelection = "- ui2_blue"
TelescopeSelectionCaret = "vivid_red ui2_blue"
TelescopeMatching = "info - bi"
TelescopeBorder = "alt_fg"
TelescopeNormal = "fg menu_bg"
TelescopePromptPrefix = "hint"
TelescopePromptTitle = "ui_orange - b"
TelescopeResultsTitle = "ui_orange - b"
TelescopePreviewTitle = "ui_orange - b"
TelescopePromptCounter = "vivid_red"
TelescopePreviewHyphen = "vivid_red"

[NvimTree]
NvimTreeFolderIcon = "link:Directory"
NvimTreeIndentMarker = "context"
NvimTreeNormal = "fg alt_bg"
NvimTreeVertSplit = "alt_bg alt_bg"
NvimTreeFolderName = "link:Directory"
NvimTreeOpenedFolderName = "folder_blue - bi"
NvimTreeEmptyFolderName = "gray - i"
NvimTreeGitIgnored = "gray - i"
NvimTreeImageFile = "light_gray"
NvimTreeSpecialFile = "orange"
NvimTreeEndOfBuffer = "alt_bg"
NvimTreeCursorLine = "- line"
NvimTreeGitStaged = "sign_add_alt"
NvimTreeGitNew = "sign_add_alt"
NvimTreeGitRenamed = "sign_add_alt"
NvimTreeGitDeleted = "sign_delete"
NvimTreeGitMerge = "sign_change_alt"
NvimTreeGitDirty = "sign_change_alt"
NvimTreeSymlink = "cyan"
NvimTreeRootFolder = "fg - b"
NvimTreeExecFile = "#9FBA89"

[Lir]
LirFloatNormal = "fg alt_bg"
LirDir = "link:Directory"
LirSymLink = "cyan"
LirEmptyDirText = "gray - i"

[Buffer]
BufferCurrent = "fg bg"
BufferCurrentIndex = "fg bg"
BufferCurrentMod = "info bg"
BufferCurrentSign = "hint bg"
BufferCurrentTarget = "vivid_red bg b"

BufferVisible = "fg bg"
BufferVisibleIndex = "fg bg"
BufferVisibleMod = "info bg"
BufferVisibleSign = "gray bg"
BufferVisibleTarget = "vivid_red bg b"

BufferInactive = "gray alt_bg"
BufferInactiveIndex = "gray alt_bg"
BufferInactiveMod = "info alt_bg"
BufferInactiveSign = "gray alt_bg"
BufferInactiveTarget = "vivid_red alt_bg b"

[StatusLine]
StatusLine = "context bg"
StatusLineNC = "line bg"
StatusLineSeparator = "line"
StatusLineTerm = "line"
StatusLineTermNC = "line"

[IndentBlankline]
IndentBlanklineContextChar = "context"
IndentBlanklineContextStart = "- - u"
IndentBlanklineChar = "dark_gray"

[Dashboard]
DashboardHeader = "blue"
DashboardCenter = "vivid_purple"
DashboardFooter = "cyan"

[DiffView]
DiffViewNormal = "gray alt_bg"
DiffviewStatusAdded = "sign_add"
DiffviewStatusModified = "sign_change"
DiffviewStatusRenamed = "sign_change"
DiffviewStatusDeleted = "sign_delete"
DiffviewFilePanelInsertion = "sign_add"
DiffviewFilePanelDeletion = "sign_delete"
DiffviewVertSplit = "- bg"

[Bookmarks]
BookmarkSign = "sign_change"
BookmarkAnnotationSign = "yellow"
BookmarkLine = "ui2_blue"
BookmarkAnnotationLine = "ui2_blue"

[Bqf]
BqfPreviewBorder = "fg"
BqfPreviewRange = "- ui2_blue"

[Cmp] # TODO
CmpItemAbbrDeprecated = "gray - s"
CmpItemAbbrMatch = "ui3_blue"
CmpItemAbbrMatchFuzzy = "ui3_blue"

CmpItemKindFunction = "ui_purple"
CmpItemKindMethod = "ui_purple"
CmpItemKindConstructor = "ui_orange"
CmpItemKindClass = "ui_orange"
CmpItemKindEnum = "ui_orange"
CmpItemKindEvent = "info"
CmpItemKindInterface = "ui_orange"
CmpItemKindStruct = "ui_orange"
CmpItemKindVariable = "light_blue"
CmpItemKindField = "light_blue"
CmpItemKindProperty = "light_blue"
CmpItemKindEnumMember = "vivid_blue"
CmpItemKindConstant = "vivid_blue"
CmpItemKindKeyword = "fg"
CmpItemKindModule = "cyan"
CmpItemKindValue = "fg"
CmpItemKindUnit = "fg"
CmpItemKindText = "fg"
CmpItemKindSnippet = "fg"
CmpItemKindFile = "fg"
CmpItemKindFolder = "fg"
CmpItemKindColor = "fg"
CmpItemKindReference = "light_blue"
CmpItemKindOperator = "fg"
CmpItemKindTypeParameter = "light_blue"

[Navic]
NavicIconsFile = "link:CmpItemKindFile"
NavicIconsModule = "link:CmpItemKindModule"
NavicIconsNamespace = "link:CmpItemKindModule"
NavicIconsPackage = "link:CmpItemKindModule"
NavicIconsClass = "link:CmpItemKindClass"
NavicIconsMethod = "link:CmpItemKindMethod"
NavicIconsProperty = "link:CmpItemKindProperty"
NavicIconsField = "link:CmpItemKindField"
NavicIconsConstructor = "link:CmpItemKindConstructor"
NavicIconsEnum = "link:CmpItemKindEnum"
NavicIconsInterface = "link:CmpItemKindInterface"
NavicIconsFunction = "link:CmpItemKindFunction"
NavicIconsVariable = "link:CmpItemKindVariable"
NavicIconsConstant = "link:CmpItemKindConstant"
NavicIconsString = "link:String"
NavicIconsNumber = "link:Number"
NavicIconsBoolean = "link:Boolean"
NavicIconsArray = "link:CmpItemKindClass"
NavicIconsObject = "link:CmpItemKindClass"
NavicIconsKey = "link:CmpItemKindKeyword"
NavicIconsKeyword = "link:CmpItemKindKeyword"
NavicIconsNull = "blue"
NavicIconsEnumMember = "link:CmpItemKindEnumMember"
NavicIconsStruct = "link:CmpItemKindStruct"
NavicIconsEvent = "link:CmpItemKindEvent"
NavicIconsOperator = "link:CmpItemKindOperator"
NavicIconsTypeParameter = "link:CmpItemKindTypeParameter"
NavicText = "gray"
NavicSeparator = "context"

[Packer]
packerString = "ui_orange"
packerHash = "ui4_blue"
packerOutput = "ui_purple"
packerRelDate = "gray"
packerSuccess = "success_green"
packerStatusSuccess = "ui4_blue"

[SymbolOutline]
SymbolsOutlineConnector = "gray"
FocusedSymbol = "- #36383F"

[Notify]
NotifyERRORBorder = "#8A1F1F"
NotifyWARNBorder = "#79491D"
NotifyINFOBorder = "ui_blue"
NotifyDEBUGBorder = "gray"
NotifyTRACEBorder = "#4F3552"
NotifyERRORIcon = "error"
NotifyWARNIcon = "warn"
NotifyINFOIcon = "ui4_blue"
NotifyDEBUGIcon = "gray"
NotifyTRACEIcon = "ui_purple"
NotifyERRORTitle = "error"
NotifyWARNTitle = "warn"
NotifyINFOTitle = "ui4_blue"
NotifyDEBUGTitle = "gray"
NotifyTRACETitle = "ui_purple"

[TreesitterContext]
TreesitterContext = "- alt_bg"

[Hop]
HopNextKey = "#4ae0ff"
HopNextKey1 = "#d44eed"
HopNextKey2 = "#b42ecd"
HopUnmatched = "gray"
HopPreview = "#c7ba7d"

[Misc]
diffAdded = "sign_add"
diffRemoved = "sign_delete"
diffFileId = "blue - br"
diffFile = "alt_bg"
diffNewFile = "green"
diffOldFile = "vivid_red"
debugPc = "- ui5_blue"
debugBreakpoint = "vivid_red - r"

CodiVirtualText = "hint"
SniprunVirtualTextOk = "hint"
SniprunFloatingWinOk = "hint"
SniprunVirtualTextErr = "error"
SniprunFloatingWinErr = "error"

DapBreakpoint = "error"

[Language]
xmlTag = "cyan"
xmlTagName = "cyan"

xmlEndTag = "cyan"
yamlPlainScalar = "orange"
yamlTSField = "blue"

luaFunc = "yellow"
luaFunction = "blue"

hclTSPunctSpecial = "alt_fg"

htmlH1 = "fg"
htmlH2 = "fg"
htmlH3 = "fg"
htmlH4 = "fg"
htmlH5 = "fg"
htmlH6 = "fg"
htmlHead = "fg"
htmlTitle = "fg"
htmlArg = "fg"
htmlTag = "blue"
htmlTagN = "blue"
htmlTagName = "blue"
htmlComment = "green"
htmlLink = "orange - u"

## css
cssBraces = "fg"
cssInclude = "vivid_purple"
cssTagName = "yellow"
cssClassName = "yellow"
cssPseudoClass = "yellow"
cssPseudoClassId = "yellow"
cssPseudoClassLang = "yellow"
cssIdentifier = "yellow"
cssProp = "fg"
cssDefinition = "fg"
cssAttr = "orange"
cssAttrRegion = "orange"
cssColor = "orange"
cssFunction = "vivid_purple"
cssFunctionName = "yellow"
cssVendor = "orange"
cssValueNumber = "orange"
cssValueLength = "orange"
cssUnitDecorators = "orange"
cssStyle = "fg"
cssImportant = "blue"

## json
jsonKeyword = "blue"

yamlBlockMappingKey = "blue"

tomlTSProperty = "blue"
